# Generated by Django 6.0.2 on 2026-02-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('restaurant', '0002_ingredient_dish_dishingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(related_name='dishes', to='restaurant.ingredient'),
        ),
        migrations.AlterField(
            model_name='cook',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='cook_set', related_query_name='cook', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='cook',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='cook_set', related_query_name='cook', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
