# Generated by Django 6.0.2 on 2026-02-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('restaurant', '0003_dish_ingredients_alter_cook_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(related_name='dishes', through='restaurant.DishIngredient',
                                         to='restaurant.ingredient'),
        ),
    ]
